export const placeholderImages = {
  hero: {
    studio: '/main.jpg',
    wedding: '/main.jpg',
    about: '/main.jpg',
  },
  carousel: [
    { src: '/img1.jpeg', alt: 'Photo studio session' },
    { src: '/img3.jpeg', alt: 'Photo studio session' },
    { src: '/img4.jpeg', alt: 'Photo studio session' },
    { src: '/img5.jpeg', alt: 'Photo studio session' },
    { src: '/img6.jpeg', alt: 'Photo studio session' },
    { src: '/img7.jpeg', alt: 'Photo studio session' },
  ],
  portfolio: [
    { id: 1, image: '/img8.jpeg', alt: 'Photo studio work' },
    { id: 2, image: '/img9.jpeg', alt: 'Photo studio work' },
    { id: 3, image: '/img10.jpeg', alt: 'Photo studio work' },
    { id: 4, image: '/img11.jpeg', alt: 'Photo studio work' },
    { id: 5, image: '/img12.jpeg', alt: 'Photo studio work' },
    { id: 6, image: '/img13.jpeg', alt: 'Photo studio work' },
    { id: 7, image: '/img14.jpeg', alt: 'Photo studio work' },
    { id: 8, image: '/img15.jpeg', alt: 'Photo studio work' },
    { id: 9, image: '/img16.jpeg', alt: 'Photo studio work' },
    { id: 10, image: '/img17.jpeg', alt: 'Photo studio work' },
    { id: 11, image: '/img18.jpeg', alt: 'Photo studio work' },
  ],
  blog: [
    '/img1.jpeg',
    '/img2.jpeg',
    '/img3.jpeg',
    '/img4.jpeg',
    '/img5.jpeg',
    '/img6.jpeg',
  ],
} as const;
